### ISSUE TITLE
Add an option to cancel/pause

### ISSUE THREAD

**Issue by Aar0wn** [fijiwebdesign/bitcast#1]
Great work, I've been searching high and low for something that operates exactly like this. I'm so delighted to find one that actually works.

I'm not very familiar with javascript, but I'll dig around and see if I could be of any help with this in regards to pausing or cancelling the stream while it's ongoing. I've just been manually killing it after backgrounding the process. Not quite sure why Ctrl-C isn't killing it.

**Comment by fijiwebdesign** [comment]
You can pause the video. The current commands are: 

```
    'stop',
    'start',
    'play',
    'pause',
    'resume',
    'volume',
    'seek'
```

I will document this when it's working properly. Right now the seek doesn't work on my samsung tv and I don't have another to test with. The otehr commands do.

Once the video starts streaming, you can just type those commands then [enter] to send the command to the device. 

let me know if that works. Sometimes Ctrl-C won't kill the process. The torrent stream can sometimes hang when you try to kill it. Not something I can look into at this point as it's within the sub modules being used.
